/*
  # Add More Family-Friendly Quests

  1. Changes
    - Add 56 new family-friendly quests
    - Points range from 1-5 based on difficulty and complexity
    - Categories include: interviews, creative activities, sports, and games
*/

INSERT INTO public.quests (title, description, points) VALUES
    ('New Year Resolution Interview', 'Ask an adult what their New Year''s resolution is', 1),
    ('Childhood Stories', 'Ask an adult what was the best part of their childhood', 1),
    ('Dream Job Discovery', 'Find out from an adult what their dream job would be', 1),
    ('Holiday Tradition Talk', 'Ask an adult about their favorite holiday tradition', 2),
    ('Book Discussion', 'Ask an adult what their favorite book is and why', 2),
    ('Year Highlights', 'Ask what was the best thing that happened to them this year', 2),
    ('Blind Sculpting', 'Create a sculpture out of play-dough with your eyes closed', 2),
    ('Superpower Chat', 'Discover what superpower an adult would choose if they could', 2),
    ('Non-Dominant Drawing', 'Draw your favorite animal using only your non-dominant hand', 2),
    ('Resolution Success Story', 'Find out if an adult has ever kept a New Year''s resolution', 2),
    ('New Year Hopes', 'Inquire about their hopes for the new year', 2),
    ('Outdoor I Spy', 'Play "I Spy" with items only outside', 2),
    ('Reverse Simon Says', 'Play "Simon Says" with a twist (e.g., Simon says in reverse)', 2),
    ('Walking Tag', 'Play a game of tag where you can only walk', 2),
    ('Memory Match', 'Play a memory game with matching cards', 2),
    ('Funny Voices', 'Sing a nursery rhyme with funny voice changes', 2),
    ('Imagination Landscape', 'Sketch a landscape from your imagination', 2),
    ('Group Riddle', 'Solve a simple riddle as a group', 2),
    ('Superhero Rescue', 'Act like a superhero saving the day from a pretend disaster', 3),
    ('World Change Discussion', 'Ask an adult what they would like to change in the world next year', 3),
    ('Magical Kitchen', 'Be a chef cooking in a magical kitchen', 3),
    ('Group Storytelling', 'Create a story where each kid adds one sentence', 3),
    ('Hockey Obstacle Course', 'Dribble a hockey ball through an obstacle course', 3),
    ('Minecraft Pet Tamer', 'Find and tame a specific animal in Minecraft', 3),
    ('Dance Competition', 'Have a 5-minute dance-off', 3),
    ('Water Balloon Challenge', 'Have a water balloon toss competition', 3),
    ('Pirate Adventure', 'Imagine you''re all on a pirate ship looking for treasure', 3),
    ('Karaoke Challenge', 'Karaoke challenge: sing any song from a list provided', 3),
    ('Magazine Art', 'Make a collage from magazine clippings', 3),
    ('Paper Airplane Contest', 'Make a paper airplane and fly it the furthest', 3),
    ('Mime Challenge', 'Mime a daily activity for others to guess', 3),
    ('Quirky Relay', 'Organize a mini relay race with quirky challenges', 3),
    ('Musical Painting', 'Paint a picture while listening to music without stopping', 3),
    ('Sock Puppets', 'Perform a puppet show with socks as puppets', 3),
    ('Party Song', 'Perform a song you make up about the party', 3),
    ('Shadow Tag', 'Play shadow tag at sunset', 3),
    ('Space Explorer', 'Pretend to be an astronaut exploring a new planet', 3),
    ('Hockey Goal', 'Score a goal from a set distance with a hockey stick', 3),
    ('Birthday Styles', 'Sing "Happy Birthday" in three different styles (e.g., opera, rap, whisper)', 3),
    ('Movie Scene', 'Act out a scene from your favorite movie or book', 4),
    ('Hockey Balance', 'Balance the hockey puck on your stick for 1 minute', 4),
    ('Card House', 'Build a card house with a deck of cards', 4),
    ('Minecraft Challenge', 'Build a house in Minecraft with specific materials only', 4),
    ('Nature Tower', 'Build the tallest structure out of sticks and leaves', 4),
    ('Minecraft Puzzle', 'Complete a puzzle challenge in Minecraft', 4),
    ('Nature Hunt', 'Create a nature scavenger hunt list and complete it', 4),
    ('News Report', 'Create a news report about today''s party', 4),
    ('Nonsense Song', 'Create and perform a song with made-up words', 4),
    ('Prop Play', 'Improvise a short play with given props', 4),
    ('Hockey Trick Shot', 'Perform a trick shot with a hockey ball', 4),
    ('Fairy Tale RPG', 'Play a game where everyone is a character from a fairy tale', 4),
    ('Minecraft Survival', 'Survive the first night in Minecraft without any weapons', 4),
    ('Juggling Practice', 'Try to juggle with soft balls or balloons', 4),
    ('Minecraft Coaster', 'Create a roller coaster in Minecraft', 5),
    ('Hockey Skills', 'Do a keepie-uppie with a hockey ball using only the stick', 5);